# Generated by Django 4.0.4 on 2022-06-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_product_price_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
