# Generated by Django 4.0.4 on 2022-06-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_category_subcategory_childcategory_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
